### ISSUE TITLE
Can this work for different model types like 2.0 and xl?

### ISSUE THREAD

**Issue by Njasa2k** [OPTML-Group/AdvUnlearn#1]
Can this work for different model types like 2.0 and xl? and what the VRAM requirement?

**Comment by damon-demon** [comment]
Theoretically, our proposed robust unlearning framework could potentially be applied to both SD v2.0 and SDXL. However, the current codebase supports only SD v1.x, which is the focus of existing DM unlearning methods. For SD v1.x, fine-tuning through AdvUnlearn with a batch size of 5 for utility-retaining regularization, requires approximately 40GB.
