### ISSUE TITLE
bash jobs/fid_10k_generate.sh takes too long to execute

### ISSUE THREAD

**Issue by xjy2020** [OPTML-Group/AdvUnlearn#4]
Hello, I haven't been able to enter the image generation stage for a long time when running bash jobs/fid_10k_generate.sh. What is the reason for this? I have already modified the content of the file in this way
`#!/bin/bash

DIRS=("")
NUMS=("9")

GPU_START=0  # GPU starting ID
GPU_END=1    # GPU ending ID

JOB_NUM=1

check_gpu() {
    GPU_ID=$1
    # Check if the number of processes is less than 2
    [[ $(nvidia-smi -i $GPU_ID --query-compute-apps=pid --format=csv,noheader | wc -l) -lt $JOB_NUM ]]
}

for dir in "${DIRS[@]}"; do 
    for num in "${NUMS[@]}"; do 
        # Find an available GPU
        GPU=-1
        while [[ $GPU -lt $GPU_START ]]; do
            for (( i=$GPU_START; i<=$GPU_END; i++ )); do
                if check_gpu $i; then
                    GPU=$i
                    break
                fi
            done

            if [[ $GPU -lt $GPU_START ]]; then
                sleep 1
            fi
        done

        CUDA_VISIBLE_DEVICES=$GPU python train-scripts/generate-example-img.py \
            --prompts_path data/prompts/coco_10k.csv \
            --folder_suffix fid_10k \
            --save_path ${dir}_$num &

        sleep 1

    done
done

wait
echo "All jobs completed."
`

**Comment by damon-demon** [comment]
> DIRS=("")
> NUMS=("9")

This part appears to be incorrect. Could you please double-check how `save_path` is used in the code? Additionally, the current script is designed to allocate one job per GPU. If a job is already running on a GPU, it will wait until that job has finished. However, you can address this issue by changing `JOB_NUM=1` to `JOB_NUM=2` or even higher.

**Comment by xjy2020** [comment]
Hello, may I take the liberty of asking again
DIRS=("")
NUMS=("999")
What are the meanings of these two lines? I didn't quite understand it, but when I execute it directly here, it will report an error of "FileNotFoundError: [Errno 2] No such file or directory:'_999. pt '". Can you give me an example?

**Comment by damon-demon** [comment]
In the script, the --save_path argument is set as `${dir}_$num`, which specifies the checkpoint directory as ${dir}_$num.
You can review the relevant code at: [GitHub link](https://github.com/OPTML-Group/AdvUnlearn/blob/526f62649ec0f26c628bf4ca87fb34dac276f47b/train-scripts/generate-example-img.py#L97).

**Comment by xjy2020** [comment]
Hello author, I noticed that you have added a causal mask to the custom text encoder in your work, while an encoder should usually have bidirectional attention. Can you explain why this is done? I will be extremely grateful.
