### ISSUE TITLE
Google drive link for checkpoints

### ISSUE THREAD

**Issue by ShimonMalnick** [OPTML-Group/AdvUnlearn#5]
Hi, the link for downloading checkpoints seems to be broken:
https://drive.google.com/drive/folders/1Nf-EJ2W3CsZwpc5blZFi7tm7o1wEiTg4?usp=sharing

Is there any updated link?

Thanks :)

**Comment by damon-demon** [comment]
Thank you for the reminder about the expired Google Drive link. The links have been updated, so please feel free to check them.
